accounts:
  - name: healthauth
    coins: ["1000token", "100000000stake"]
    mnemonic: "input price beyond scare demise display artefact hurdle until waste decide symbol choice crater rose above cigar blame segment scene current impose sunny void"
  - name: alice 
    coins: ["1000token"]
    mnemonic: "satisfy ticket tornado intact whale sleep field gate rule unfair enemy winner mouse damp harvest error iron scissors primary you deer all rebel write"
  - name: relayer
    address: "cosmos1rjnx254jxdhe52yh6ek68c457rq5j956hwxmr8"
    coins: ["100000000stake"]
validator:
  name: healthauth 
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: alice
  coins: ["5token"]
  host: ":4501"
init:
  home: ".home"
genesis:
  chain_id: "muggleAuth"
  app_state:
    vac:
      credentialList: [{"claim":2,"creator":"cosmos1d3569vdcjt2cjff2mmqlk782hs07pjhr0mq0g3","holder":"did:muggleAuth:fl5492k6uuqgent27lyp9tfwz5te50hm425k4f","id":"0","issuer":"did:muggleAuth:d3569vdcjt2cjff2mmqlk782hs07pjhr0mq0g3"}]
host:
  rpc: ":26657"
  p2p: ":26658"
  prof: ":6060"
  grpc: ":9091"
  api: ":1337"
