// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: credential/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetRecvProofRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetRecvProofRequest) Reset()         { *m = QueryGetRecvProofRequest{} }
func (m *QueryGetRecvProofRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecvProofRequest) ProtoMessage()    {}
func (*QueryGetRecvProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbeeac0030699d6, []int{0}
}
func (m *QueryGetRecvProofRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecvProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecvProofRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecvProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecvProofRequest.Merge(m, src)
}
func (m *QueryGetRecvProofRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecvProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecvProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecvProofRequest proto.InternalMessageInfo

func (m *QueryGetRecvProofRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetRecvProofResponse struct {
	RecvProof *RecvProof `protobuf:"bytes,1,opt,name=RecvProof,proto3" json:"RecvProof,omitempty"`
}

func (m *QueryGetRecvProofResponse) Reset()         { *m = QueryGetRecvProofResponse{} }
func (m *QueryGetRecvProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecvProofResponse) ProtoMessage()    {}
func (*QueryGetRecvProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbeeac0030699d6, []int{1}
}
func (m *QueryGetRecvProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecvProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecvProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecvProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecvProofResponse.Merge(m, src)
}
func (m *QueryGetRecvProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecvProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecvProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecvProofResponse proto.InternalMessageInfo

func (m *QueryGetRecvProofResponse) GetRecvProof() *RecvProof {
	if m != nil {
		return m.RecvProof
	}
	return nil
}

type QueryAllRecvProofRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRecvProofRequest) Reset()         { *m = QueryAllRecvProofRequest{} }
func (m *QueryAllRecvProofRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRecvProofRequest) ProtoMessage()    {}
func (*QueryAllRecvProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbeeac0030699d6, []int{2}
}
func (m *QueryAllRecvProofRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRecvProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRecvProofRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRecvProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRecvProofRequest.Merge(m, src)
}
func (m *QueryAllRecvProofRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRecvProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRecvProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRecvProofRequest proto.InternalMessageInfo

func (m *QueryAllRecvProofRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRecvProofResponse struct {
	RecvProof  []*RecvProof        `protobuf:"bytes,1,rep,name=RecvProof,proto3" json:"RecvProof,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRecvProofResponse) Reset()         { *m = QueryAllRecvProofResponse{} }
func (m *QueryAllRecvProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRecvProofResponse) ProtoMessage()    {}
func (*QueryAllRecvProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbeeac0030699d6, []int{3}
}
func (m *QueryAllRecvProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRecvProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRecvProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRecvProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRecvProofResponse.Merge(m, src)
}
func (m *QueryAllRecvProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRecvProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRecvProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRecvProofResponse proto.InternalMessageInfo

func (m *QueryAllRecvProofResponse) GetRecvProof() []*RecvProof {
	if m != nil {
		return m.RecvProof
	}
	return nil
}

func (m *QueryAllRecvProofResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetRecvProofRequest)(nil), "whalelephant.certx.credential.QueryGetRecvProofRequest")
	proto.RegisterType((*QueryGetRecvProofResponse)(nil), "whalelephant.certx.credential.QueryGetRecvProofResponse")
	proto.RegisterType((*QueryAllRecvProofRequest)(nil), "whalelephant.certx.credential.QueryAllRecvProofRequest")
	proto.RegisterType((*QueryAllRecvProofResponse)(nil), "whalelephant.certx.credential.QueryAllRecvProofResponse")
}

func init() { proto.RegisterFile("credential/query.proto", fileDescriptor_9bbeeac0030699d6) }

var fileDescriptor_9bbeeac0030699d6 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x3d, 0x8f, 0xd3, 0x30,
	0x1c, 0xc6, 0xeb, 0xf0, 0x22, 0x61, 0x10, 0x83, 0x07, 0x54, 0x22, 0x88, 0x50, 0x06, 0xa8, 0x2a,
	0x61, 0xd3, 0x22, 0x5e, 0xd6, 0x32, 0xb4, 0x6b, 0xc9, 0x84, 0xd8, 0x9c, 0xe4, 0x4f, 0x6a, 0xc9,
	0x8d, 0xd3, 0xd8, 0x2d, 0x54, 0x88, 0x85, 0x4f, 0x80, 0xc4, 0xd7, 0x60, 0x43, 0x7c, 0x07, 0xc6,
	0x4a, 0xb7, 0xdc, 0x78, 0x6a, 0xef, 0x2b, 0xdc, 0x7e, 0x6a, 0x92, 0x6b, 0x52, 0x35, 0x77, 0xed,
	0xdd, 0x92, 0x21, 0xfe, 0x3f, 0x8f, 0x7f, 0xcf, 0x63, 0x1b, 0x3f, 0x0a, 0x52, 0x08, 0x21, 0x36,
	0x82, 0x4b, 0x36, 0x99, 0x42, 0x3a, 0xa7, 0x49, 0xaa, 0x8c, 0x22, 0x4f, 0xbf, 0x8e, 0xb8, 0x04,
	0x09, 0xc9, 0x88, 0xc7, 0x86, 0x06, 0x90, 0x9a, 0x6f, 0xb4, 0x1c, 0xb5, 0x9f, 0x44, 0x4a, 0x45,
	0x12, 0x18, 0x4f, 0x04, 0xe3, 0x71, 0xac, 0x0c, 0x37, 0x42, 0xc5, 0x3a, 0x17, 0xdb, 0xed, 0x40,
	0xe9, 0xb1, 0xd2, 0xcc, 0xe7, 0x1a, 0x72, 0x57, 0x36, 0xeb, 0xf8, 0x60, 0x78, 0x87, 0x25, 0x3c,
	0x12, 0x71, 0x36, 0x5c, 0xcc, 0xda, 0x15, 0x80, 0x14, 0x82, 0xd9, 0x30, 0x55, 0xea, 0x4b, 0xbe,
	0xe6, 0xb6, 0x71, 0xf3, 0xe3, 0x5a, 0x3d, 0x00, 0xe3, 0x5d, 0x2c, 0x79, 0x30, 0x99, 0x82, 0x36,
	0xe4, 0x21, 0xb6, 0x44, 0xd8, 0x44, 0xcf, 0x50, 0xeb, 0xb6, 0x67, 0x89, 0xd0, 0x0d, 0xf0, 0xe3,
	0x9a, 0x59, 0x9d, 0xa8, 0x58, 0x03, 0xe9, 0xe3, 0x7b, 0x9b, 0x9f, 0x99, 0xe6, 0x7e, 0xb7, 0x45,
	0xaf, 0x4c, 0x48, 0x4b, 0x93, 0x52, 0xea, 0xfa, 0x05, 0x50, 0x4f, 0xca, 0x1d, 0xa0, 0x3e, 0xc6,
	0x65, 0xb8, 0x62, 0x93, 0xe7, 0x34, 0x6f, 0x82, 0xae, 0x9b, 0xa0, 0x79, 0xbf, 0x45, 0x13, 0x74,
	0xc8, 0x23, 0x28, 0xb4, 0x5e, 0x45, 0xe9, 0xfe, 0x41, 0x45, 0x92, 0xed, 0x4d, 0xea, 0x93, 0xdc,
	0xba, 0x61, 0x12, 0x32, 0xd8, 0xa2, 0xb5, 0x32, 0xda, 0x17, 0x7b, 0x69, 0x73, 0x88, 0x2a, 0x6e,
	0xf7, 0xcc, 0xc2, 0x77, 0x32, 0x5c, 0xf2, 0x0f, 0x55, 0xd8, 0xc8, 0xbb, 0x3d, 0x54, 0x97, 0x1d,
	0xac, 0xfd, 0xfe, 0xfa, 0xc2, 0x1c, 0xcb, 0x7d, 0xf3, 0xf3, 0xe8, 0xf4, 0xb7, 0xc5, 0xc8, 0x4b,
	0x56, 0x75, 0x60, 0x99, 0x03, 0xab, 0xbb, 0x66, 0xec, 0xbb, 0x08, 0x7f, 0x90, 0xbf, 0x08, 0x3f,
	0xd8, 0x98, 0xf5, 0xa4, 0x3c, 0x0c, 0xbd, 0xe6, 0x0a, 0x1c, 0x86, 0x5e, 0x77, 0xac, 0xee, 0xab,
	0x0c, 0xbd, 0x4d, 0x5a, 0x87, 0xa2, 0x7f, 0x18, 0xfe, 0x5f, 0x3a, 0x68, 0xb1, 0x74, 0xd0, 0xc9,
	0xd2, 0x41, 0xbf, 0x56, 0x4e, 0x63, 0xb1, 0x72, 0x1a, 0xc7, 0x2b, 0xa7, 0xf1, 0xf9, 0x6d, 0x24,
	0xcc, 0x68, 0xea, 0xd3, 0x40, 0x8d, 0x77, 0xdd, 0x3e, 0x15, 0xdf, 0x2d, 0x57, 0x33, 0x4f, 0x40,
	0xfb, 0x77, 0xb3, 0x47, 0xf7, 0xfa, 0x3c, 0x00, 0x00, 0xff, 0xff, 0x64, 0x28, 0xc0, 0xb6, 0x13,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a recvProof by id.
	RecvProof(ctx context.Context, in *QueryGetRecvProofRequest, opts ...grpc.CallOption) (*QueryGetRecvProofResponse, error)
	// Queries a list of recvProof items.
	RecvProofAll(ctx context.Context, in *QueryAllRecvProofRequest, opts ...grpc.CallOption) (*QueryAllRecvProofResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RecvProof(ctx context.Context, in *QueryGetRecvProofRequest, opts ...grpc.CallOption) (*QueryGetRecvProofResponse, error) {
	out := new(QueryGetRecvProofResponse)
	err := c.cc.Invoke(ctx, "/whalelephant.certx.credential.Query/RecvProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecvProofAll(ctx context.Context, in *QueryAllRecvProofRequest, opts ...grpc.CallOption) (*QueryAllRecvProofResponse, error) {
	out := new(QueryAllRecvProofResponse)
	err := c.cc.Invoke(ctx, "/whalelephant.certx.credential.Query/RecvProofAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a recvProof by id.
	RecvProof(context.Context, *QueryGetRecvProofRequest) (*QueryGetRecvProofResponse, error)
	// Queries a list of recvProof items.
	RecvProofAll(context.Context, *QueryAllRecvProofRequest) (*QueryAllRecvProofResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RecvProof(ctx context.Context, req *QueryGetRecvProofRequest) (*QueryGetRecvProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvProof not implemented")
}
func (*UnimplementedQueryServer) RecvProofAll(ctx context.Context, req *QueryAllRecvProofRequest) (*QueryAllRecvProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvProofAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RecvProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRecvProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecvProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/whalelephant.certx.credential.Query/RecvProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecvProof(ctx, req.(*QueryGetRecvProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecvProofAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRecvProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecvProofAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/whalelephant.certx.credential.Query/RecvProofAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecvProofAll(ctx, req.(*QueryAllRecvProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "whalelephant.certx.credential.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecvProof",
			Handler:    _Query_RecvProof_Handler,
		},
		{
			MethodName: "RecvProofAll",
			Handler:    _Query_RecvProofAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credential/query.proto",
}

func (m *QueryGetRecvProofRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecvProofRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecvProofRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecvProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecvProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecvProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecvProof != nil {
		{
			size, err := m.RecvProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRecvProofRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRecvProofRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRecvProofRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRecvProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRecvProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRecvProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RecvProof) > 0 {
		for iNdEx := len(m.RecvProof) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RecvProof[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetRecvProofRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetRecvProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RecvProof != nil {
		l = m.RecvProof.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRecvProofRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRecvProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RecvProof) > 0 {
		for _, e := range m.RecvProof {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetRecvProofRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecvProofRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecvProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecvProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecvProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecvProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecvProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RecvProof == nil {
				m.RecvProof = &RecvProof{}
			}
			if err := m.RecvProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRecvProofRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRecvProofRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRecvProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRecvProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRecvProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRecvProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecvProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecvProof = append(m.RecvProof, &RecvProof{})
			if err := m.RecvProof[len(m.RecvProof)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
